version: "2"
services:
  agridies:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    env_file:
      - sample.env         # CHANGEME
    environment:
      MYSQL_ROOT_PASSWORD: $$MYSQL_PASSWORD
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
